demo_name_path: data/demo_names.json
demo_stats_path: data/demo_stats.json
goal_int_resources_path: evaluation/goal_interpretation/resources
subgoal_dec_resources_path: evaluation/subgoal_decomposition/resources
subgoal_vocab_path: evaluation/subgoal_decomposition/resources/base_vocabulary.json